version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest-arm64
    environment:
      - SERVICES=s3,sns,lambda,apigateway,sqs
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - "4566:4566"
      - "4571:4571"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./localstack-init:/etc/localstack/init/ready.d

  lambda:
    build: ../app
    environment:
      - AWS_REGION=us-east-1
    depends_on:
      - localstack

